### ISSUE TITLE
Job listing refinements

### ISSUE THREAD

**Issue by nokome** [stencila/hub#1016]
Some issues with display of jobs:

- [ ] Child jobs have status "Unknown" until their parent is started (should be same as parent ie Waiting or at least Pending)
- [x] Pending jobs have run time displayed but should really have a dash.
- [x] For consistency it feels like there should a dot between the status tag and the user
- [x] For consistency it feels like there should an icon for the anonymous user

![image](https://user-images.githubusercontent.com/1152336/107902652-f5459180-6fab-11eb-9d4f-84dc4e49bb46.png)

**Comment by alex-ketch** [comment]
What do you think of keeping the anonymous users listed as `Anonymous` for clarity and consistency with the filter dropdown option?

https://github.com/stencila/hub/blob/ca41069fe002f4af0da97fa83229c0f8fe72443a/manager/projects/templates/projects/jobs/_job_item.html#L37-L41

---

We should also probably not list all pages, and instead show ~10-15 total, with +/- 5 pages either side of the current page.

![Screenshot 2021-02-15 at 10 06 54](https://user-images.githubusercontent.com/1646307/107963487-3de25800-6f76-11eb-93b8-1946bd2bedc8.png)

**Comment by alex-ketch** [comment]
Closing and moving the last outstanding item into its own issue
> Child jobs have status "Unknown" until their parent is started (should be same as parent ie Waiting or at least Pending
