### ISSUE TITLE
Relabel: "Search Username" -> "Add team memeber"

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#110]

**Comment by beneboy** [comment]
@apawlik This conflicts #91 which removed the label all together. Which way do we want to go?

**Comment by apawlik** [comment]
@beneboy  Good point. At the moment we have `Search for a user` which I think is better than `Add team member` or empty. So I am closing this issue. Let's leave it as is. I will try to go though all search boxes in forms to ensure consistency.
