### ISSUE TITLE
Creating teams under accounts: short text if there are no projects

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#111]
Currently there is a drop down list - which, if there are no projects doesn't work.

**Comment by beneboy** [comment]
Added two messages depending on the reason that there's no access:

> This Team already has access to all projects in this Account.

or 

> There are no Projects for this account, please <a href="{% url 'project_create' %}">create a
                            Project</a>, then come back here to grant this Team access to it.

Hopefully it is clear under which scenario each will show :)
