### ISSUE TITLE
Require email at registration to enable password reset

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#133]
Currently we don't require email address during account registration which will create problems when the user forgets their username and/or the password. There will be no way to reset it and they will lose access to their account and potentially projects. 
We will also end up with lots of ghost accounts.

**Comment by colettedoughty** [comment]
27/07/2020 This issue has been fixed. See screen shot. 
![image](https://user-images.githubusercontent.com/64813273/88492421-d88d4080-cffe-11ea-86af-aa1f48e61ca4.png)
