### ISSUE TITLE
Project # instead of name when opening

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#137]
When opening the project instead of its name (which the user will be familiar with), the Hub displays the internal # number 
![image](https://user-images.githubusercontent.com/2358535/47828892-b181ea80-dde9-11e8-874e-dfff8e4b95ae.png)

**Comment by beneboy** [comment]
This page is going to be obsoleted soon (we are planning to remove checkouts) so I haven't done too much to this, just had it show the name of the project and no input if the project id is passed in the URL.
