### ISSUE TITLE
Setup asynchronous queues

### ISSUE THREAD

**Issue by nokome** [stencila/hub#14]
An asynchronous queue system is needed for a number of things. e.g. to initialise a component in a newly activated session (need to wait for session to start up).

Looks like https://django-q.readthedocs.org may be an easier alternative to setup than Celery and give within-Django ability to setup custom schedules, for example for re-rendering stencils.

**Comment by apawlik** [comment]
Code base changed so this appears to be obsolete. We may have a similar issue but it would have different specs. Closing
