### ISSUE TITLE
Permissions: don't have access to my own projects

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#148]
I know we had that before but I cannot see find the issue. I cannot access my own projects (get Access Denied modal).

**Comment by beneboy** [comment]
@apawlik Is this just since my code pushed yesterday?

Is this on your local install or on Stencila test?

**Comment by apawlik** [comment]
@beneboy I'm on Stencila Test. Trying things out before I ask the testers to run some work. The strange thing is that I just created a new project and this one I can access. But I have some old ones that I cannot. The same with the old ones under my Account.

**Comment by nokome** [comment]
I believe this has been resolved.
