### ISSUE TITLE
Teams: adding a user that doesn't exist results in 405

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#157]
Trying to add a user that does not exist in the Hub, results in 405 (related to https://github.com/stencila/hub/issues/141 ?) 

It should return an error saying something like "user doesn't exist" etc.

**Comment by beneboy** [comment]
Fixed in b52e3f2

**Comment by apawlik** [comment]
Hm, I am still getting the error

**Comment by beneboy** [comment]
I fixed this for Team previously but the error still existed for adding members to account. I wonder if we got confused there. Anyway it will be fixed for adding users to the account at next release.
