### ISSUE TITLE
Repo unlink duplicate

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#161]
Even though attempting to link GH repo via the full address gives error, it does show up for unlinking

![image](https://user-images.githubusercontent.com/2358535/49844189-c90bb480-fe26-11e8-8d2a-22cb53e3844d.png)

**Comment by beneboy** [comment]
I could not replicate this, when I tried to link using a URL it would not give me an error and I was unable to unlink it.

I have fixed it up though now so you can use just the username/repo OR the full URL and it will parse the url/repo for you. Plus added better validation.

**Comment by apawlik** [comment]
Thanks!
