### ISSUE TITLE
Project: duplicated GH repositories linking

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#164]
If the repository is already linked as source of files, the Hub should not allow for linking it again
![image](https://user-images.githubusercontent.com/2358535/50071327-432ca680-0236-11e9-9093-5a1ae79b1a15.png)

**Comment by alex-ketch** [comment]
Currently the Hub fails silently when trying to add an already linked source.
I will create a new issue to improve the messaging/UX around this.
