### ISSUE TITLE
Worker management

### ISSUE THREAD

**Issue by nokome** [stencila/hub#17]
At present there is none. Implement a simple bin packing algo which usese a select query like `ram_avail_gt=ram and cpu_avail_gt=cpu` order by `-sessions` . Needs some definition of ram_avail and cpu_avail (and ram_total etc) units on worker models

**Comment by apawlik** [comment]
Code base changed - this issue is somewhat obsolete. We will need though a management of resources per session thus replaced by high-level issue #48
