### ISSUE TITLE
Add Intercom button

### ISSUE THREAD

**Issue by nokome** [stencila/hub#177]
Add an Intercom button so that users can get help from within the Hub.

There's a package for integration https://github.com/kencochrane/django-intercom (not sure if it's needed or how useful it is).

FWIW, this is how we integrated Intercom three years ago (although things might have changed a wee bit since then :).

https://github.com/stencila/hub/blob/cc91e5c418e98557a64f685a91188a41390eccbf/director/general/templates/base.html#L37-L39

https://github.com/stencila/hub/blob/cc91e5c418e98557a64f685a91188a41390eccbf/director/general/templates/_header.html#L28-L32

**Comment by beneboy** [comment]
Added in 8671fe52b66b9af4920640f5c35e5a0001834f24
