### ISSUE TITLE
Creating project zip archive

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#188]
Replaces #183 

Add a feature which enables users create a snapshot (zipped archive) of their project which can be downloaded.
Implementation could be:
- adding a tab in the project view `Archives`
- under that tab all archives (zipped files) of the projects are listed
- add a button under that tab `Archive now`

Each archive has also a timestamp

**Comment by apawlik** [comment]
Possibly we should allow for the option of creating the name or tagging the archive so that it is clear, for the purpose of a training course for example, which zip file is a submission to the assignment.

**Comment by beneboy** [comment]
Have added the ability to create and the zip files automatically get the date in the name. There is no control of this from the user end so they can't create a fake name with a date in the past.

They can add a tag though which is prepended to the archive name. But there is no way of getting rid of the date.
