### ISSUE TITLE
Browser support: notifications

### ISSUE THREAD

**Issue by nokome** [stencila/hub#198]
Currently were are using ES6 template literals and other modern JavaScript features for in page UI enhancements. These are not supported by IE and a few other browsers.

- [ ] In the short term we need to let users using unsupported browsers, that they are unsupported.

In the longer term we'll move to compiling modern ES6 or Typescript to widely supported Javascript

**Comment by apawlik** [comment]
Will try to have a go at it, thanks to @beneboy guidance

**Comment by alex-ketch** [comment]
Have we established a list of browser versions we want to officially support?

**Comment by beneboy** [comment]
@alex-ketch Not yet, at this stage it's just "not IE" since it doesn't support ES6.

**Comment by beneboy** [comment]
Done in f4b345e9209fa5dac5f40e225e637f4fbef993a1
