### ISSUE TITLE
Formats and endpoints for integration with Google Docs and Google Sheets

### ISSUE THREAD

**Issue by nokome** [stencila/hub#212]
We need a way for users to be able to convert executable documents from formats like RMarkdown and Excel to Google Docs and Google Sheets.

GDocs and GSheets can be represented as JSON. Over in `stencila/convert` repo we have nascent converters for these formats which use the media types and file extensions:

- `.gdoc` `application/vnd.google-apps.document`
- `.gsheet` `application/vnd.google-apps.sheet`

Using these formats directly, instead of uploading/downloading via a format like `xlsx` or `docx` is advantageous because it (a) skips a conversion step and thus should be less lossy and error prone (b) allows us to make use of things like [metadata in sheets](https://developers.google.com/sheets/api/guides/metadata).

The hub will use the binary of the converter to convert to/from these formats and then use the following API endpoints to `POST` and `GET` them from Google. Note that at this time, syncing a document, ie. `PUT` or `PATCH` it, is out of scope.

### `gsheet` files

- create a `gsheet` using the [`create` API method](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/create)
- service = discovery.build('sheets', 'v4', credentials=credentials)
request = service.spreadsheets().create(body=gsheet)
response = request.execute()
- get the `gsheet` using the [`get` API method](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets/get)
- service = discovery.build('sheets', 'v4', credentials=credentials)
service.spreadsheets().get(spreadsheetId=spreadsheet\_id, ranges=ranges, includeGridData=include\_grid\_data)
response = request.execute()

Not sure how/if we need to reconstitute the response to `gsheet` JSON.

### `gdoc` files

- unfortunately the GDocs [`create` API method](https://developers.google.com/docs/api/reference/rest/v1/documents/create) will only create a blank document and unlike the analogous endpoint for sheets "Other fields in the request, including any provided content, are ignored." Providing content may be enabled in the future, but in the meantime we need to use an intermediate format and the [Google Drive import method](https://developers.google.com/drive/api/v3/manage-uploads#import_to_google_docs_types_). We could use a variety of formats for this, but I suggest that we convert `gdoc` to `html` and then import that (the `html` converter is currently better developed than the `docx` converter and easier to debug):
- file\_metadata = {
'name': paper.title,
'mimeType': 'application/vnd.google-apps.document'
}
media = MediaFileUpload('project/paper.gdoc',

                      mimetype='text/html',
                  resumable=True)

- file = drive\_service.files().create(body=file\_metadata,

                                  media_body=media,
                              fields='id').execute()

- get the `gdoc` using the [`get` API method](https://developers.google.com/docs/api/reference/rest/v1/documents/get)
- service = discovery.build('docs', 'v1', credentials=credentials)
gdoc = service.documents().get(documentId=document\_id).execute()

**Comment by alex-ketch** [comment]
Closing as we've now taken a different approach and this issue isn't relevant any more.
