### ISSUE TITLE
Clarify text when creating a new file

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#216]
Currently when creating a new file, we show the user the Project number instead of the name.
We should ideally reinforce the user's location by showing them the project name to avoid potentially confusion and hesitation.

The subtext:
> "File will be created in directory"

is also a little confusing as we don't tell the user relative which directory the file would be created at. Besides potentially improving the text, something to explore could be to parse the provided path and show the user where the file will be created.

![Screen Shot 2019-04-30 at 18 56 48](https://user-images.githubusercontent.com/1646307/56998574-b85f9f00-6b79-11e9-899b-6e15e484b4d5.png)

**Comment by beneboy** [comment]
This is redundant as part of the redesign

![image](https://user-images.githubusercontent.com/292725/57002219-f7413380-6c11-11e9-8cae-dd9e798ba0ae.png)
