### ISSUE TITLE
[Draft] Implement endpoint(s) for programatic interactions

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#220]
For upcoming projects we'd like to programatically interact with the Hub. Below is a draft of some proposed interactions that we'd like to have, but we don't have to strive to implement all of them at once.

**Desired operations:**
- Authenticate
	- Sign In
	- Sign Out
	- Sign Up?
- List Projects and their metadata
- Execute code blocks/expressions, returning results as rPNGs
	- Error messaging
- List data files associated with a project
	- Add/Link data files?
	- Remove data files?
- Change assigned project (might need to clarify behaviour for this)
- Conversion between file formats
- Publish/visibility settings

**Comment by beneboy** [comment]
This is a draft server plan and some of these choices might change if they aren't the best option when we implement them.

Going with REST API at the moment, to ease development effort (c.f. GraphQL, will reevaluate that in the future).

Initially endpoints will be for
- sign in
- sign out
- Project list
  - Only metadata is `id` and `name`

We plan to use Swagger for documentation (Django REST Swagger).

JSON output data will be "normalizd" as per https://github.com/paularmstrong/normalizr.

For example, project list format:

```json
{
    "entities": {
        "projects": {
            "1": {"id": "1", "name": "Project 1"},
            "2": {"id": "2", "name": "Project 2"},
    },
    "result": ["1", "2"]
}
```

**Comment by alex-ketch** [comment]
Something that @nokome and I were discussing over lunch was where the responsibility of listing code chunks/expressions belonged.

The two potential separations of concerns we were discussing were:
- Having Hub proxy a yet to be determined (micro-)service which can parse the Stencila node tree and return list/locations of code-chunks
- Having the client parse the document/stencila node tree, identify code elements, translating them to context specific location markers.

My hesitation for doing code-chunk identification just on client side is that I'd like to be cautious about us having to write the same logic in multiple places for each client.

Having said that, the current intuition is that for the scope of this issue we can write client specific logic, and then review to see what can be extracted.
Though I think we'll likely need both at some point.
- On the backend for reducing initial workload on client side during renders, as well as potentially allowing for direct interactions with the code chunks on the Hub (table of contents, stats, linting/validating, ??)
- On the client side for responsive interactions while editing content (adding/removing paragraphs, inserting new code-chunks, etc). I think waiting for a full network call will result in a subpar and clunky experience.

Thoughts or comments @beneboy, @nokome ?

---

**Proposed scope for initial version as of today:**
- Authenticate
  - Sign In
  - Sign Out
- Projects
  - List projects & metadata
  - Associate document with project
  - (Stretch): Create project
- (Stretch): Files
  - List file associated with a project
  - Link/upload files to a project

**Out of scope:**
- Proxy code chunk/expression execution requests

**Comment by nokome** [comment]
Given that this is now almost a year old, and that most this initial list in implemented e.g. https://hub.stenci.la/api/docs/ I will close this. New issues for specific changes / additions to API more than welcome!
