### ISSUE TITLE
Saving and retrieving components

### ISSUE THREAD

**Issue by nokome** [stencila/hub#23]
ATM, when a user creates a new component (e.g. `/stencils/new`) nothing gets persisted. Users need to be able to save their own clone of a component and then retrieve it later.

Also need a page for viewing a list of components `/components/` and specific component types `/sheets/`.

This is related to https://github.com/stencila/stencila/issues/132 but it's primarily a hub issue so repeating it here.

**Comment by apawlik** [comment]
Obsolete since code base changed and the way Stencila documents are created and saved.
