### ISSUE TITLE
Links in footer of /open document preview are not clickable.

### ISSUE THREAD

**Issue by nokome** [stencila/hub#251]
On the document preview page e.g. https://hub-test.stenci.la/open/9jQ56vUg7oD the links in the footer are not clickable:

![image](https://user-images.githubusercontent.com/1152336/65485560-54f25700-def6-11e9-8d81-f7d74a58d5fb.png)

**Comment by beneboy** [comment]
I couldn't replicate this even on the link you provided. Could you do some experimenting and see what the cause could be, maybe the margin under the iframe is too short and it goes above the footer? Or you have some cached CSS.

**Comment by nokome** [comment]
The issue seems to be that `<footer class="footer conversions-footer">` is over the top of `<footer class="footer open-footer">`. As intended the former footer is not present when you follow the share link so it is only a problem with the user who does the initial conversion.

**Comment by beneboy** [comment]
I see! OK I'll check it out.
