### ISSUE TITLE
/open: not resolving HacKMD when URL has query parameters

### ISSUE THREAD

**Issue by nokome** [stencila/hub#254]
HackMD appends `?edit`, `?view` etc to note URLs. We want users to be able to copy and paste HackMD URLs into open but that is currently failing because the query parameters make `/open` think it's just a normal HTML page:

https://hub.stenci.la/open/https://hackmd.io/RaFYCFoyTlODFxz5hPevLw?edit

Note that query parameters on GDoc URLs do not affect resolution.

**Comment by beneboy** [comment]
Fixed in c964c9e
