### ISSUE TITLE
Allow iframe loading of Stencila HTML & assets from external domain

### ISSUE THREAD

**Issue by davidcmoulton** [stencila/hub#284]
eLife need to load the Stencila hub-hosted HTML (& referenced assets) via an iframe. To allow this load will require the Content Security Policy on the server that hosts the HTML etc to allow 3rd party iframing. From https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors it'd look something like: 

```
Content-Security-Policy: frame-ancestors https://elifesciences.org https://*.elifesciences.org;
```

For IE support, [`X-Frame-Options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) should be changed to `allow-from` the same url-scheme as above.

**Comment by beneboy** [comment]
I've added both headers as requested. To activate them on a published or preview url, you need to add `?elife` to the Hub URL

So the iframe source would be something like:

https://hub.stenci.la/elife/projectname/path/to/doc?elife

**Comment by nokome** [comment]
This is now deployed e.g.

```curl
nokome@pluto ~ [124]> curl -iL "https://hub.stenci.la/elife/homo-naledi-exploratory-testing/elifesciences.org-to-jats-to-html.html?elife"
HTTP/1.1 301 Moved Permanently
Server: nginx/1.17.8
Date: Fri, 07 Feb 2020 02:34:36 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Location: /elife/homo-naledi-exploratory-testing/elifesciences.org-to-jats-to-html.html/?elife
Via: 1.1 google
Alt-Svc: clear

HTTP/1.1 200 OK
Server: nginx/1.17.8
Date: Fri, 07 Feb 2020 02:34:36 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 44043
Content-Security-Policy: frame-ancestors https://elifesciences.org https://*.elifesciences.org;
X-Frame-Options: allow-from https://*.elifesciences.org
Vary: Cookie
Via: 1.1 google
Alt-Svc: clear
````
