### ISSUE TITLE
broker: Move redis from TCP to Unix sockets

### ISSUE THREAD

**Issue by nokome** [stencila/hub#34]
Unix sockets gives better performance https://github.com/NodeRedis/node_redis#rediscreateclient.
- [ ] Add redis configuration as per `TODO` in `stencila/web/collab/Store.js` (stencila/stencila repo)
- [ ] Uncomment `unixsocket` settings in `broker/redis.conf`

**Comment by apawlik** [comment]
Code base changed. Closing
