### ISSUE TITLE
Place configuration values in an Env file

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#355]
> What do you think about making an issue for extracting these (`POSTHOG_KEY`, `SENTRY_DSN`, plus any other similar values) into some sort of `env` file down the road. That way if someone pulls and deploys the HUB, they don't end up polluting/sending events to our account?

_Originally posted by @alex-ketch in https://github.com/stencila/hub/pull/351_

**Comment by nokome** [comment]
Another suggestion from @beneboy was to ensure that the config used in tests is a similar as possible to prod. I just ran into that as an issue again and have created a `Test` config class that is separate from `Dev`:

https://github.com/stencila/hub/blob/a8778e304dee4fa7778ded07221b024445a6395f/director/settings.py#L400-L415

It also occurred to me that config sprawl / inconsistencies could be reduced by using `Prod` as the base class and `Dev` and `Test` only overriding what is necessary.

Just leaving these as notes here, with intention of a separate PR focused on this.
