### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [stencila/hub#36]
Is it possible to move to ASL 2.0 inline with rest of the repos?

**Comment by nokome** [comment]
Yes, this was the intension. Will probably be done as part of forthcoming
reorganization of this repo.

Thanks for the input!

**Comment by sirinath** [comment]
Wondering how the reorganisation is going?

**Comment by nokome** [comment]
Hey @sirinath, as you can see nothing has happened yet. Currently aiming for end of January.
