### ISSUE TITLE
fix(Sign in): Should respect the next parameter

### ISSUE THREAD

**Issue by nokome** [stencila/hub#368]
While working on #357 I noticed that the signin form does not seem to be respecting the `next` parameter e.g. `http://localhost:8000/me/signin/?next=/api/nodes/third-project-codechunk.html`. It always redirects to dashboard?

**Comment by beneboy** [comment]
Signing in with username/password or social auth?

**Comment by nokome** [comment]
Just checked on prod: problem only happens when signing in with username/password (FWIW, signing in with both Github and ORCID both fine and redirected to `next`).
