### ISSUE TITLE
Add functionality to delete a project from the Hub UI

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#402]
Currently there isn't a way to delete projects from the Hub UI.
I've currently encountered a need to do so after creating several demo projects and now my dashboard is cluttered with unwanted projects.

**Comment by nokome** [comment]
I agree this is a high priority. Regarding UX, I propose that we use the same "please confirm by entering the name of the project" approach of Github.

![image](https://user-images.githubusercontent.com/1152336/80925312-ceceb500-8de2-11ea-9123-62ffb049d2b9.png)

There are more sophisticated things we could do like putting project in the "Trash" (for potential recovery) but that introduces a lot more code throughout (e.g. having to filter project by `trashed=false`)
