### ISSUE TITLE
Proposal: Rename "Accounts" to "Organizations"

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#403]
@nokome and I discussed about bringing the nomenclature and UX to be closer to other platforms users might be familiar with.
I was personally initially confused because I consider the word "Account" and "User" interchangeable, so always takes me an extra second to remember which one I want to use on the Hub.

I propose that we bring alignment to the GitHub model by:
- referring to "Accounts" as "Organizations"
- the user's personal account (currently named `<username>s-personal-account`) is shortened to be just their `username`
- considerations need to be made for presenting user personal "account/organization" alongside with their "user" settings for things like projects, sharing, and compute plans

**Repercussions:**
- Rename "Accounts" to "Organizations" throughout the UI (Hamburger menu, breadcrumbs, New Project view, Account/Org member settings view, etc.)
- Personal Account settings view will need to hide "Teams" and "Members" tabs/settings (Both left and right sidebars) under `Home / Accounts / :account` (the Account overview page)
- Remove the "This account has N projects" text above the list of projects on the Account overview page
- Hide the `Identity` section for personal Accounts under the Account Settings view
- Changing username should rename the Organization

**Comment by nokome** [comment]
Thanks for posting this @alex-ketch. To be a little more specific, I don't think we should change the name of the `Account` model but rather:

1. add a field to the `Account` model as a flag of whether and account is personal or not: boolean, or a `ForeignKey` to the user?
2. present non-personal `Account`s as "Organizations", and
3. present personal `Account` settings, along side their user settings (as you say)

**Comment by simonwinter** [comment]
I think it would also be great to have some linkage between the user's settings page & their account profile. 

i.e. adding a link on here:

![image](https://user-images.githubusercontent.com/1104537/82624064-d4772800-9c35-11ea-8aa8-bf9e8b2a9761.png)

to:

![image](https://user-images.githubusercontent.com/1104537/82624104-e8bb2500-9c35-11ea-8bbe-e8e13caa1426.png)

Should we also style the user's account differently on the account list page? It should always be displayed first & highlighted differently IMO.

![image](https://user-images.githubusercontent.com/1104537/82624227-2324c200-9c36-11ea-8f3f-1da75f0c6268.png)

**Comment by simonwinter** [comment]
Wait .... /accounts becomes /organisations ... so you actually don't need to show the users' account in the list of accounts, so no need to highlight them ... right?

**Comment by alex-ketch** [comment]
> Wait .... /accounts becomes /organisations ... so you actually don't need to show the users' account in the list of accounts, so no need to highlight them ... right?

Yeah, I don't think it's necessary. Though it would be desirable to make the username in the hamburger menu link to the User's personal Account/Org profile view (the second screenshot in your comment above)

![Screenshot 2020-05-21 at 22 20 01](https://user-images.githubusercontent.com/1646307/82624882-b962d480-9bb1-11ea-9eb4-797fab97bd28.png)

**Comment by alex-ketch** [comment]
Closing, see https://github.com/stencila/hub/pull/472#issuecomment-646443497

> This refactoring / renaming is now part of the manager service (which will replace director). So closing this PR.
