### ISSUE TITLE
Uploaded files modification times

### ISSUE THREAD

**Issue by nokome** [stencila/hub#41]
File modification dates for `StencilaProjects` should use the users local time not UTC

![image](https://user-images.githubusercontent.com/1152336/41447443-6be88dba-70a9-11e8-8df1-9b077c32b68e.png)

**Comment by apawlik** [comment]
This is done now (?)

![image](https://user-images.githubusercontent.com/2358535/49836216-b5e8ec80-fe06-11e8-82c4-3a61eecde07e.png)
