### ISSUE TITLE
Resolve and mount project files into compute Session

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#419]
**When creating a Session**
- Checkout all files into a temporary working directory, and mount it inside the session. (Remote/Linked files should be downloaded as part of the mounting process)

This is required to be able to execute documents containing linked data files.

**Comment by nokome** [comment]
This has been done and deployed for snapshots:

![image](https://user-images.githubusercontent.com/1152336/89753523-c1853d00-db2c-11ea-8f72-5719dc2cc3be.png)

Loving the themed table output :heart_eyes: 

![image](https://user-images.githubusercontent.com/1152336/89753663-2e003c00-db2d-11ea-8c1a-388ae156e6f2.png)

Soon we will want to enable this for project working directories, currently it just mounts snapshot directories. Closing this particular issue however.
