### ISSUE TITLE
Round of CSS polish

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#434]
- [x] Refine scale relationships between texts and icons
![CleanShot 2020-05-12 at 00.26.21@2x.png](https://images.zenhubusercontent.com/5eb4c5db73211e2c9ab4a791/d6a127ff-97df-47b6-9c45-b5739c222806)

- [ ] Remove padding around field groups in `Project Settings` view to improve alignment, and avoid fields being hidden

![CleanShot 2020-05-12 at 00.27.37@2x.png](https://images.zenhubusercontent.com/5eb4c5db73211e2c9ab4a791/38958e58-6c56-4b1e-ab77-201f3506bc26)

**Comment by simonwinter** [comment]
Hi @alex-ketch I'm looking at something like this for the user dashboard - what do you think?

![image](https://user-images.githubusercontent.com/1104537/82608038-0c6a7500-9c0e-11ea-921e-fc8337c4522e.png)

I've reduced the icon size to medium and removed a couple of classes that were breaking the layout (pushing the icon out to the edge of the container).

**Comment by alex-ketch** [comment]
That's a drastic improvement @simonwinter, though I think we can go a tad smaller on the icon and match it to the text size. Right now it still feels too heavy visually to me.
What do you think about something like this:

![dashboard](https://user-images.githubusercontent.com/1646307/82611133-cb328080-9b8d-11ea-80ea-55ddabaaa910.png)

**Comment by alex-ketch** [comment]
Second bullet point is still an issue, reopening

**Comment by simonwinter** [comment]
> Second bullet point is still an issue, reopening

Hi @alex-ketch this should be resolved in the current branch I'm working on (css-refactor) + I think the personal-accounts branch as well. Once the css-refactor branch is merged, you should be able to close this.

**Comment by alex-ketch** [comment]
Closing as this has been addressed in the `manager` service (which will replace `director`).
