### ISSUE TITLE
Refine Jobs UI view

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#453]
This is continuation of https://github.com/stencila/hub/pull/448:

- [ ] Split out to #458 ~~Convert Job ID to hash. Add a new field to the Job database . Show first seven characters from the hash in the Job log overview page.~~
- [x] Change sort order of to be newest job to oldest
- [x] Make job row clickable to go to details
- [x] Swap job token and status text information so that the job type is in the coloured token, and the status below it
- [x] Hide Job runtime until the `began` field is populated. If Job still in progress calculate ongoing run time till present, if completed then calculate total run time.

Feel free to split some of these out into their own issues if it makes more sense to you @nokome, @simonwinter

**Comment by simonwinter** [comment]
I'm working on these (bar the hash ID which @nokome will work on) on the [ui-updates](https://github.com/stencila/hub/tree/ui-updates) branch

**Comment by alex-ketch** [comment]
Closed by #457
