### ISSUE TITLE
Two options for adding a data file to project

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#46]
Feature suggested by @nokome 

When adding a data file to a project the user can decide whether they want it to be opened as a Stencila Sheet (in a separate tab) or loaded directly into a data frame, in which case the file would not open as a Stencila Sheet.

Notes:
* Should we enable this only for `csv` files? 
* What should be the default setting for the `read_csv` function that will read that data?
* User should have a choice between `Read as Pandas DataFrame` or `Read as R DataFrame`
* User should still be able to open the DataFrame as a Stencila Sheet.

**Comment by alex-ketch** [comment]
Closing as the workflows on the Hub have changed significantly.
We can revisit later if/when the need arises.
