### ISSUE TITLE
Add new users to waiting list

### ISSUE THREAD

**Issue by colettedoughty** [stencila/hub#475]
Currently anyone can sign up and create a new account but we cant provide support for too many people so we want to allow people to sign up as users and add them to a waiting list. 

- [x] add field to users to indicate they are on wait list
- [ ] re direct waitlist users to a holding page which tells them things they might want to look up. eg GitHub repos & Discord etc.

**Comment by nokome** [comment]
I think this can be closed now. We do not have a "holding page", instead we show users they are on the "Waiting List" plan.
