### ISSUE TITLE
How should we capture the splash images of projects for gallery?

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#53]
Projects in [the Hub Gallery](https://drive.google.com/file/d/1uYPat6AiNxD_AilDSk9WTzMM_FcS6R5O/view?usp=sharing) should ideally have an attractive screenshot - ideally with an image. We could use the first available figure in the project:
1) any figure
2) figure/plot generated by the user's code

If there is not figure whatsoever - a "screenshot" from the top (Title) down to?

**Comment by nokome** [comment]
Superseded by #871
