### ISSUE TITLE
Allow a setting Docker image execution contexts for Sessions

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#600]
To ensure that projects with varying dependencies are able to be successfully executed, we'd like to provide a way to set the Docker image within which to run the project.

Current plan is to have a project setting similar to the `Theme` selector, but alternatives could include looking for a `Dockerfile` in the project files.

Relates to #419

**Comment by nokome** [comment]
Done and should be available in the next release.

![image](https://user-images.githubusercontent.com/1152336/95285830-3c18d180-08be-11eb-995b-3e142459a20b.png)

Also include pinning of the image at the time of snapshotting:

![image](https://user-images.githubusercontent.com/1152336/95285935-77b39b80-08be-11eb-9318-aa77423ca602.png)
