### ISSUE TITLE
Snaps: Generate snapshots of pages with URL queries

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#606]
When generating the page snapshots in https://github.com/stencila/hub/blob/master/manager/scripts/create_page_snaps.py, we don't include pages with URL queries such as for specific Project file details.
This causes us to have an incomplete overview of the Hub UI and performance.

Relates to #605

**Comment by nokome** [comment]
This has been resolved, for sources and files, with this: https://github.com/stencila/hub/commit/616212af5e3fe62aed8723a187bad560f003ccf0

Also related is https://github.com/stencila/hub/commit/512a1976de3602acaf34d31f2c56e4150eef876a which visits some pages with multiple users.

This will be an ongoing chore: checking to see which paths are dispalyed as `Skipping: ....` and adding them. But closing this specific issue.
