### ISSUE TITLE
Missing targets in Makefile

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#63]
Target: `setup` depends on `director-setup` and `director-env` Neither of the two exist. 
@nokome is that on purpose? Or just hasn't been updated? If the latter, I can fix it and PR.

**Comment by nokome** [comment]
Thanks, yes, it just hasn't been updated for names changes / deletions made to the sub recipes. It should be:

> setup: director-venv

No need to PR that, just a commit in master will do

**Comment by apawlik** [comment]
Will do

**Comment by apawlik** [comment]
Closed via https://github.com/stencila/hub/commit/83414f4ac542dff3ff1198e0ae20a3f3e0846d56
