### ISSUE TITLE
Create our version of Fail Whale for 404, 403 and 500 errors

### ISSUE THREAD

**Issue by apawlik** [stencila/hub#69]

**Comment by beneboy** [comment]
@jwijay I remember you said you wanted something to display when projects was empty. This one is probably low priority but would also be cool to do.

**Comment by nokome** [comment]
+1 to this. Particularly while things are in development, and these sort of errors are more likely to occur, it's useful to have a message that is engaging and fun and hopefully reduces user frustration a little. A link for some inspiration: https://rigor.com/blog/15-awesome-fail-pages

**Comment by nokome** [comment]
FWIW, and to bump this, I just got a rare Github fail page:

![image](https://user-images.githubusercontent.com/1152336/59388913-e233e600-8d21-11e9-8d02-a48831bb92ff.png)

**Comment by nokome** [comment]
We still don't have this fail whale page for 500 errors. I just got this:

![image](https://user-images.githubusercontent.com/1152336/65469069-2fdff300-deba-11e9-853b-05d668410b5f.png)

 It would be good to:

- [ ] Stylistically have something more like the "Ooops" page @jwijay created for https://github.com/stencila/hub/pull/242. I suggest we use the same image, just change the text.
- [ ] Allow the user to provide some more information by creating an issue on Github with a link like https://github.com/stencila/hub/issues/new?title=Critical+error+on+page+xxxx&labels=bug&body=The+error+id+yyyy+happend+when+I... 

@beneboy : I feel that this is fairly high priority, would you be able to resolve this issue?
