### ISSUE TITLE
Remove signout confirmation?

### ISSUE THREAD

**Issue by nokome** [stencila/hub#7]
Django-allauth asks for signout confirmation. Can be annoying:  "I would never recommend a site asking to confirm to sign out unless signing in was particularly painful"

Reason for logout confirm http://django-allauth.readthedocs.org/en/latest/views.html and how to bypass it http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/#Remove_the_logout-confirmation_step

**Comment by peakboyq** [comment]
> Django-allauth asks for signout confirmation. Can be annoying: "I would never recommend a site asking to confirm to sign out unless signing in was particularly painful"
> 
> Reason for logout confirm http://django-allauth.readthedocs.org/en/latest/views.html and how to bypass it http://www.sarahhagstrom.com/2013/09/the-missing-django-allauth-tutorial/#Remove_the_logout-confirmation_step
