### ISSUE TITLE
Add support for Google Sheets as a Project Source option

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#711]
We used to support Google Docs integration, which [would like to re-implement](https://github.com/stencila/hub/issues/710).
In addition we should add support for Google Sheets files in a similar fashion.

![Screenshot 2020-09-23 at 13 10 56](https://user-images.githubusercontent.com/1646307/94046129-47d4a600-fd9e-11ea-9d2f-c396d81d2026.png)

Related issue:

- https://github.com/stencila/hub/issues/212

**Comment by nokome** [comment]
This is d-d-done:

![Uploading image.png…]()
