### ISSUE TITLE
API/Client refinements for fetching user specific resources

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#743]
Two limitations with the current API footprint are blocking some work we have planned.

- Ability to retrieve list of Accounts for which a user can create a project.
  - Not sure if we want to go with the same route as https://github.com/stencila/hub/pull/708, or have something like `GET /users/me/accounts`, `GET /users/me/projects`, `GET /users/me/teams`, etc.
- Currently only name and username is returned by `GET /users/{me|id}`, for future work (https://github.com/stencila/gsuita/issues/22, https://github.com/stencila/gsuita/issues/34) we'd like to also show the user's avatar and email address returned.

**Comment by nokome** [comment]
> Not sure if we want to go with the same route as #708, or have something like GET /users/me/accounts, GET /users/me/projects, GET /users/me/teams, etc.

I suggest that we use the same filtering approach for accounts as in #708 (which was for projects). In that case `GET /accounts?role=member` would be the same as `GET /users/me/accounts`.

**Comment by nokome** [comment]
Mmm, actually we already have filtering by role, account type and search string but it is not documented and thus those parameters do not make it into the schema and thus do not make it into the client APIs. e.g `http://127.0.0.1:8000/api/accounts?search=&role=member&is=org` is used for filtering from page `http://127.0.0.1:8000/orgs/`
