### ISSUE TITLE
Pricing page

### ISSUE THREAD

**Issue by colettedoughty** [stencila/hub#770]
Hub [pricing page](https://hub.stenci.la/pricing/) improvements

- Change the order of the pricing categories. Free to the left, Pro in the middle. Team to the right.
- Make the $ sign smaller than the number value.

**Comment by nokome** [comment]
To get the correct order do something like this in https://github.com/stencila/hub/blob/master/manager/manager/ui/views.py#L45

```
def pricing(request: HttpRequest) -> HttpResponse:
    """
    Pricing page view.

    Served at /pricing/
    """
    tiers = AccountTier.objects.orby_by('id').all()
    return render(request, "accounts/plans.html", dict(tiers=tiers))
```
