### ISSUE TITLE
Add projects & plan to the top right dropdown menu

### ISSUE THREAD

**Issue by colettedoughty** [stencila/hub#772]
When you sign into the hub you have a column on the left hand side with projects, settings and plan but once you start navigating around the site working on things you quickly lose this column and easy access to your projects and plan. 

In the top right hand corner is a drop down menu.  if you click settings you can get access to your projects and plan as the column comes back onto the page. This is not an obvious step and feels cumbersome.  Adding plan and projects to the right hand drop-down menu would be much easier for users. 

![image](https://user-images.githubusercontent.com/64813273/96801335-d9017000-1463-11eb-93aa-853b02d84a21.png)

**Comment by nokome** [comment]
After discussing with @colettedoughty we decided the best place for a "My Projects" link was under the "Projects" main nav menu:

![image](https://user-images.githubusercontent.com/1152336/97373612-3fcad180-191b-11eb-86d6-c5e256b8b50b.png)

I have added a similar menu option for organisations "My Organizations".
