### ISSUE TITLE
Better prompting to signin with same third party account as last time

### ISSUE THREAD

**Issue by nokome** [stencila/hub#8]
Currently we have this on signin page:

![image](https://cloud.githubusercontent.com/assets/1152336/11676495/9e48f466-9e97-11e5-98a3-ecfc291ca7d6.png)

Rather than relying on users to remember which third party account they used perhaps could have a cookie which record which account was used to login with last time and only show that as an option. Only show this warning message if no cookie.

**Comment by apawlik** [comment]
Potentially consider implementing solutions discussed here https://github.com/pennersr/django-allauth/issues/277 for merging two accounts (if user accidentally logged in with two different 3rd party accounts)

**Comment by apawlik** [comment]
Doesn't seem to work at the moment (?) Need to investigate.

**Comment by apawlik** [comment]
This still needs to be addressed even though this is an old issue. Also related to https://github.com/stencila/hub/issues/93

**Comment by nokome** [comment]
After researching this a little again, the best thread, with the most concrete solutions and recent comments is this one: https://github.com/pennersr/django-allauth/issues/418#issuecomment-107880925 (starting there and going down). 

That provides a strategy for connecting a new social account to an existing Django account. It uses exact email matches. We might also want to consider close matches, including names not just emails, and present the user with a list of those similar accounts which they may instead want to authenticate with (and then link the new social account to after?). Recognising that there are several security concerns here.

Also to note that this issue was originally suggesting something simpler - just keeping a cookie that suggests to the user that they re-authenticate on the Hub using the same social account as last time.

**Comment by richardmansfield** [comment]
Addressed as part of https://github.com/stencila/hub/pull/474, but someone needs to look at the user prompting. The PR just sets the "primary" class on the button for the last login provider, so the button goes purple instead of black.
