### ISSUE TITLE
List of files in Snapshot detail view is always empty

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#870]
Even though the Snapshot contains files, the UI fails to list them.

![Screenshot 2020-11-30 at 16 21 49](https://user-images.githubusercontent.com/1646307/100667257-438db180-3328-11eb-8c69-89edb0e515a0.png)

**Comment by nokome** [comment]
Closed in 71e5133df8e13f9c58ee489a1af93911c6fd68f6
