### ISSUE TITLE
Add a curated projects gallery view to use as a landing page

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#872]
To make the platform more visually appealing for new and existing users, we'd like to replace the current landing page (the project search results view) with an updated design that highlights articles.
This will also allow us to present curated list of articles and have themed collections, etc.

This issue would benefit from completing #871 first.

Some of the elements to consider including could be:

- a featured image for the project
- the abstract
- project keywords/tags
- authors/accounts
- DOI to give a better sense of authority/validity to articles
- "Quick Run" ERA button
- Date published/updated

Whilst working on this issue, we should also address the ordering mechanic for the projects and close https://github.com/stencila/hub/issues/55.

**Comment by alex-ketch** [comment]
Preview of work in progress to get a rough idea of the current direction. @nokome, please feel free to chime in with feedback about the layout, content, or something else.

![Screenshot 2020-12-09 at 15 57 46](https://user-images.githubusercontent.com/1646307/101686886-ac1b1380-3a37-11eb-832d-7be3172bf169.png)

**Comment by nokome** [comment]
Thanks @alex-ketch, looks good. My only suggestions is to move the private and role icons off the image and into the footer. That feels more consistent, avoids clutter over the image and places more emphasis on the CTA Run button.
