### ISSUE TITLE
Snapshots: Add "target" and "rel" attributes to external anchor links

### ISSUE THREAD

**Issue by alex-ketch** [stencila/hub#878]
Often the Snapshots are served from an iFrame, e.g. in the Snapshot details view on the Hub, or a published ERA article embedded on a journal's website.
In order to ensure that external links found in the document open in the right context, we should add `target="_top"` and `rel="noreferrer noopener"` attributes to external links.

One consideration here is whether to use `target="_top"` vs `target="_blank"` attribute.

- `_blank`: will open links in a new browser tab or window
- `_top`: will follow normal browser patterns, opening in the user's current browser tab/window, but allow opening in a new tab if they `Ctrl/Cmd + click` the link

Given expected article content, I think using `_blank` could be an ok assumption to support opening multiple reference links to support exploring the linked content without losing the current place in the ERA article.
I'm happy to hear counter-arguments for this assumption though :)

Once this issue is in place, we can remove the eLife specific fix added in https://github.com/stencila/thema/pull/238 to eliminate unnecessary client side JS operations.

**Comment by FAtherden-eLife** [comment]
I agree that `_blank` would be suitable.
